name: Fetch Remote Markdown and Build

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print current directory
      run: pwd

    - name: List files in the repository
      run: ls -la

    - name: Make fetch script executable
      run: chmod +x ./fetch_remote_md.sh

    - name: Fetch remote markdown file
      run: ./fetch_remote_md.sh

    - name: List files after fetching markdown
      run: ls -la _includes/md

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2' # Specify the Ruby version your Jekyll site uses

    - name: Install Bundler
      run: gem install bundler

    - name: Install dependencies
      run: bundle install

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Jupyter
      run: pip3 install --upgrade jupyter

    - name: Build Jekyll site
      run: bundle exec jekyll build